### ISSUE TITLE
fix user styles

### ISSUE THREAD

**Issue by jahan-addison** [jahan-addison/gridpaste#138]
Fix homepage alignment:
![img](https://d3r69eeiwn2k86.cloudfront.net/items/2w0L1Q1k0v2W2K1G0B3T/Image%202019-05-16%20at%2011.37.09%20PM.png?v=b4205d33)

Fix error styles, make them red: See #115 for notification errors issue

![img](https://d3r69eeiwn2k86.cloudfront.net/items/1L0Y3L433W3i0r442x3t/Image%202019-05-16%20at%2011.37.20%20PM.png?v=ba2ac068)

also, fix the submit button - add this to `container.scss`:

```scss
input[type="submit"] {
 outline: none;
  border: none;
}
```
